export const WORKBOOK = [
  [
    {
      Name: 'Campaign1',
      Budget: '1111',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'enabled',
      BrandEntityId: 'id1',
      BidOptimization: 'true',
      BidMultiplier: '45',
      PortfolioId: '23432',
      Creative_BrandName: 'CreativeBrandName1',
      Creative_BrandLogoAssetId: 'BrandLogoAssetId1',
      Creative_Headline: 'headline1',
      Creative_Asins: 'creativeasin1, creativeasin2, creativeasin3',
      LandingPage_Asins: 'landingpageasin1, landingpageasin2, landingpage3',
      LandingPage_Url: 'http://www.landingpageurl1.com',
      rowIndex: 0,
      errorCount: 0,
      status: null,
    },
    {
      Name: 'Campaign2',
      Budget: '2222',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id2',
      BidOptimization: 'true',
      BidMultiplier: '46',
      PortfolioId: '4243',
      Creative_BrandName: 'CreativeBrandName2',
      Creative_BrandLogoAssetId: 'BrandLogoAssetId2',
      Creative_Headline: 'headline2',
      Creative_Asins: 'creativeasin5, creativeasin6, creativeasin7',
      LandingPage_Asins: 'landingpageasin1, landingpageasin2, landingpage4',
      LandingPage_Url: 'http://www.landingpageurl1.com',
      rowIndex: 1,
      errorCount: 0,
      status: null,
    },
    {
      Name: 'Campaign3',
      Budget: '3333',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id3',
      BidOptimization: 'false',
      BidMultiplier: '47',
      PortfolioId: '2345',
      Creative_BrandName: 'CreativeBrandName3',
      Creative_BrandLogoAssetId: 'BrandLogoAssetId3',
      Creative_Headline: 'headline3',
      Creative_Asins: 'creativeasin8, creativeasin9, creativeasin10',
      LandingPage_Asins: 'landingpageasin1, landingpageasin2, landingpage5',
      LandingPage_Url: 'http://www.landingpageurl1.com',
      rowIndex: 2,
      errorCount: 0,
      status: null,
    },
    {
      Name: 'Campaign4',
      Budget: '4444',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'paused',
      BrandEntityId: 'id4',
      BidOptimization: 'true',
      BidMultiplier: '67',
      PortfolioId: '564',
      Creative_BrandName: 'CreativeBrandName4',
      Creative_BrandLogoAssetId: 'BrandLogoAssetId4',
      Creative_Headline: 'headline4',
      Creative_Asins: 'creativeasin11, creativeasin12, creativeasin13',
      LandingPage_Asins: 'landingpageasin1, landingpageasin2, landingpage6',
      LandingPage_Url: 'http://www.landingpageurl1.com',
      rowIndex: 3,
      errorCount: 0,
      status: null,
    },
    {
      Name: 'Campaign5',
      Budget: '5555',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'enabled',
      BrandEntityId: 'id5',
      BidOptimization: 'false',
      BidMultiplier: '88',
      PortfolioId: '6878',
      Creative_BrandName: 'CreativeBrandName5',
      Creative_BrandLogoAssetId: 'BrandLogoAssetId5',
      Creative_Headline: 'headline5',
      Creative_Asins: 'creativeasin14, creativeasin15, creativeasin16',
      LandingPage_Asins: 'landingpageasin1, landingpageasin2, landingpage7',
      LandingPage_Url: 'http://www.landingpageurl1.com',
      rowIndex: 4,
      errorCount: 0,
      status: null,
    },
  ], // SBK_Campaigns
  [
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText1',
      NativeLanguageKeyword: 'language1',
      NativeLanguageLocale: 'Local1',
      MatchType: 'broad',
      Bid: '234',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText2',
      NativeLanguageKeyword: 'language2',
      NativeLanguageLocale: 'Local2',
      MatchType: 'phrase',
      Bid: '235',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText3',
      NativeLanguageKeyword: 'language3',
      NativeLanguageLocale: 'Local3',
      MatchType: 'broad',
      Bid: '236',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText4',
      NativeLanguageKeyword: 'language4',
      NativeLanguageLocale: 'Local4',
      MatchType: 'exact',
      Bid: '237',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText5',
      NativeLanguageKeyword: 'language5',
      NativeLanguageLocale: 'Local5',
      MatchType: 'broad',
      Bid: '238',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText6',
      NativeLanguageKeyword: 'language6',
      NativeLanguageLocale: 'Local6',
      MatchType: 'broad',
      Bid: '239',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText7',
      NativeLanguageKeyword: 'language7',
      NativeLanguageLocale: 'Local7',
      MatchType: 'phrase',
      Bid: '240',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText8',
      NativeLanguageKeyword: 'language8',
      NativeLanguageLocale: 'Local8',
      MatchType: 'exact',
      Bid: '241',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText9',
      NativeLanguageKeyword: 'language9',
      NativeLanguageLocale: 'Local9',
      MatchType: 'broad',
      Bid: '242',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText10',
      NativeLanguageKeyword: 'language10',
      NativeLanguageLocale: 'Local10',
      MatchType: 'exact',
      Bid: '243',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText11',
      NativeLanguageKeyword: 'language11',
      NativeLanguageLocale: 'Local11',
      MatchType: 'phrase',
      Bid: '244',
      rowIndex: 10,
      errorCount: 0,
    },
  ], // SBK_Keywords
  [
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText1',
      MatchType: 'negativeExact',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText2',
      MatchType: 'negativePhrase',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText3',
      MatchType: 'negativeExact',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText4',
      MatchType: 'negativeExact',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText5',
      MatchType: 'negativePhrase',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText6',
      MatchType: 'negativeExact',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText7',
      MatchType: 'negativePhrase',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText8',
      MatchType: 'negativePhrase',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText9',
      MatchType: 'negativeExact',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText10',
      MatchType: 'negativeExact',
      rowIndex: 9,
      errorCount: 0,
    },
  ], // SBK_NegativeKeywords
];
